theme: jekyll-theme-minimal
title: Leetcode Tracker
description: Tracking Ryan Foo's algorithms progress
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Week 1
    url: /week-1
  - title: Week 2
    url: /week-2
  - title: Week 3
    url: /week-3
  - title: Week 4
    url: /week-4